version: "3.7"

services:
  redis:
    image: redis:
    ports:
      - 6379:6379

  cineweb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/srv/app/src
      - ./config:/srv/app/config
      - ./logs:/srv/app/logs
    ports:
      - 3000:3000
